# Generated by Django 6.0.3 on 2026-03-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_model',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
