# Generated by Django 6.0 on 2026-03-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_first_model_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_model',
            name='high_role',
            field=models.CharField(default=0),
        ),
    ]
