# Generated by Django 6.0 on 2026-03-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_first_model_high_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_model',
            name='group_name',
            field=models.CharField(default=50),
        ),
    ]
