# Generated by Django 6.0.3 on 2026-03-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_first_model_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='second_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('month_mentor', models.CharField(max_length=40)),
            ],
        ),
    ]
