# Generated by Django 6.0.3 on 2026-03-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_second_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='assistants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('group', models.IntegerField(default=0)),
            ],
        ),
    ]
